name: E-max
favicon: null
layout_spectrum: 0.24708
typography_spectrum: 0.18026
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.625
  lightness: 0.1875
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
