name: E-max
favicon: null
layout_spectrum: 0.46298234281130135
typography_spectrum: 0.1417745603248477
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6815063869580626
  lightness: 0.1492494335398078
  saturation: 0.36611948092468083
  rhythmicContrast: 0.141129961470142
purpose: []
